var annotated_dup =
[
    [ "cgpnt", "workarea_8h.html#structcgpnt", "workarea_8h_structcgpnt" ],
    [ "font", "bios__const_8h.html#structfont", "bios__const_8h_structfont" ],
    [ "metasprite", "group__SPRITES__METASPRITE.html#structmetasprite", "group__SPRITES__METASPRITE_structmetasprite" ],
    [ "OPLL", "group__OPLL__DEVICE.html#structOPLL", "group__OPLL__DEVICE_structOPLL" ],
    [ "OPLL_Device", "structOPLL__Device.html", "structOPLL__Device" ],
    [ "ResourceIndex", "group__RESOURCES__FIND.html#structResourceIndex", "group__RESOURCES__FIND_structResourceIndex" ],
    [ "SCC", "group__SCC__DEVICE.html#structSCC", "group__SCC__DEVICE_structSCC" ],
    [ "SCC_buffer", "group__SCC__BUFFER.html#structSCC__buffer", "group__SCC__BUFFER_structSCC__buffer" ],
    [ "SCC_Channel", "group__SCC__DEVICE.html#structSCC__Channel", "group__SCC__DEVICE_structSCC__Channel" ],
    [ "SCC_Device", "group__SCC__DEVICE.html#structSCC__Device", "group__SCC__DEVICE_structSCC__Device" ],
    [ "SCC_Waveform", "group__SCC__DEVICE.html#structSCC__Waveform", "group__SCC__DEVICE_structSCC__Waveform" ],
    [ "snd_EventTrack", "structsnd__EventTrack.html", "structsnd__EventTrack" ],
    [ "snd_Instrument", "group__SNDDRV__DATA.html#structsnd__Instrument", "group__SNDDRV__DATA_structsnd__Instrument" ],
    [ "snd_Music", "group__SNDDRV__DATA.html#structsnd__Music", "group__SNDDRV__DATA_structsnd__Music" ],
    [ "snd_p_table", "group__SNDDRV__DATA.html#structsnd__p__table", "group__SNDDRV__DATA_structsnd__p__table" ],
    [ "snd_Pattern", "group__SNDDRV__DATA.html#structsnd__Pattern", "group__SNDDRV__DATA_structsnd__Pattern" ],
    [ "snd_Pattern.channels", "group__SNDDRV__DATA.html#structsnd__Pattern_8channels", "group__SNDDRV__DATA_structsnd__Pattern_8channels" ],
    [ "snd_Pattern.specialChannels", "group__SNDDRV__DATA.html#structsnd__Pattern_8specialChannels", "group__SNDDRV__DATA_structsnd__Pattern_8specialChannels" ],
    [ "snd_SoundAssets", "group__SNDDRV__DATA.html#structsnd__SoundAssets", "group__SNDDRV__DATA_structsnd__SoundAssets" ],
    [ "snd_SpeedTrack", "structsnd__SpeedTrack.html", "structsnd__SpeedTrack" ],
    [ "snd_Track", "structsnd__Track.html", "structsnd__Track" ],
    [ "sound_clip", "group__SOUND__OLD__API.html#structsound__clip", "group__SOUND__OLD__API_structsound__clip" ],
    [ "sound_eg_AHDSR", "group__SOUND__OLD__EG__API.html#structsound__eg__AHDSR", "group__SOUND__OLD__EG__API_structsound__eg__AHDSR" ],
    [ "sound_eg_attribute", "group__SOUND__OLD__EG__API.html#structsound__eg__attribute", "group__SOUND__OLD__EG__API_structsound__eg__attribute" ],
    [ "sound_eg_attribute.__unnamed3__", "group__SOUND__OLD__EG__API.html#unionsound__eg__attribute_8____unnamed3____", "group__SOUND__OLD__EG__API_unionsound__eg__attribute_8____unnamed3____" ],
    [ "sound_eg_LPCM", "group__SOUND__OLD__EG__API.html#structsound__eg__LPCM", "group__SOUND__OLD__EG__API_structsound__eg__LPCM" ],
    [ "sound_fragment", "group__SOUND__OLD__API.html#structsound__fragment", "group__SOUND__OLD__API_structsound__fragment" ],
    [ "sprite", "group__SPRITES__ATTR.html#structsprite", "group__SPRITES__ATTR_structsprite" ],
    [ "sprite_color", "group__SPRITES__COLOR.html#structsprite__color", "group__SPRITES__COLOR_structsprite__color" ],
    [ "TTY_Device", "structTTY__Device.html", "structTTY__Device" ],
    [ "vdp_cmd", "group__VDP__COMMANDS__LOW.html#structvdp__cmd", "group__VDP__COMMANDS__LOW_structvdp__cmd" ],
    [ "vec2i", "group__SPRITES__METASPRITE.html#structvec2i", "group__SPRITES__METASPRITE_structvec2i" ]
];