var annotated_dup =
[
    [ "metasprite", "metasprite_8h.html#structmetasprite", "metasprite_8h_structmetasprite" ],
    [ "SCC", "scc_8h.html#structSCC", "scc_8h_structSCC" ],
    [ "SCC_Channel", "scc_8h.html#structSCC__Channel", "scc_8h_structSCC__Channel" ],
    [ "SCC_Device", "scc_8h.html#structSCC__Device", "scc_8h_structSCC__Device" ],
    [ "snd_EventTrack", "structsnd__EventTrack.html", "structsnd__EventTrack" ],
    [ "snd_Instrument", "snd__i__table_8h.html#structsnd__Instrument", "snd__i__table_8h_structsnd__Instrument" ],
    [ "snd_Music", "snd__sound_8h.html#structsnd__Music", "snd__sound_8h_structsnd__Music" ],
    [ "snd_p_table", "snd__p__table_8h.html#structsnd__p__table", "snd__p__table_8h_structsnd__p__table" ],
    [ "snd_Pattern", "snd__sound_8h.html#structsnd__Pattern", "snd__sound_8h_structsnd__Pattern" ],
    [ "snd_Pattern.channels", "snd__sound_8h.html#structsnd__Pattern_8channels", "snd__sound_8h_structsnd__Pattern_8channels" ],
    [ "snd_Pattern.specialChannels", "snd__sound_8h.html#structsnd__Pattern_8specialChannels", "snd__sound_8h_structsnd__Pattern_8specialChannels" ],
    [ "snd_SoundAssets", "snd__sound_8h.html#structsnd__SoundAssets", "snd__sound_8h_structsnd__SoundAssets" ],
    [ "snd_SpeedTrack", "structsnd__SpeedTrack.html", "structsnd__SpeedTrack" ],
    [ "snd_Track", "structsnd__Track.html", "structsnd__Track" ],
    [ "sound_clip", "sound_8h.html#structsound__clip", "sound_8h_structsound__clip" ],
    [ "sound_eg_AHDSR", "sound__eg_8h.html#structsound__eg__AHDSR", "sound__eg_8h_structsound__eg__AHDSR" ],
    [ "sound_eg_attribute", "sound__eg_8h.html#structsound__eg__attribute", "sound__eg_8h_structsound__eg__attribute" ],
    [ "sound_eg_attribute.__unnamed3__", "sound__eg_8h.html#unionsound__eg__attribute_8____unnamed3____", "sound__eg_8h_unionsound__eg__attribute_8____unnamed3____" ],
    [ "sound_eg_LPCM", "sound__eg_8h.html#structsound__eg__LPCM", "sound__eg_8h_structsound__eg__LPCM" ],
    [ "sound_fragment", "sound_8h.html#structsound__fragment", "sound_8h_structsound__fragment" ],
    [ "sprite", "sprite_8h.html#structsprite", "sprite_8h_structsprite" ],
    [ "sprite.__unnamed5__", "sprite_8h.html#unionsprite_8____unnamed5____", "sprite_8h_unionsprite_8____unnamed5____" ],
    [ "sprite_color", "sprite__color_8h.html#structsprite__color", "sprite__color_8h_structsprite__color" ],
    [ "vdp_cmd", "vdp_8h.html#structvdp__cmd", "vdp_8h_structvdp__cmd" ],
    [ "vec2i", "metasprite_8h.html#structvec2i", "metasprite_8h_structvec2i" ]
];