var searchData=
[
  ['in_20banked_20memory_0',['in banked memory',['../group__RESOURCES__FIND.html',1,'Find a resource in banked memory.'],['../group__RESOURCES__INDIRECT__ACCESS.html',1,'Reading and copying from resource in banked memory.']]],
  ['individual_20address_20spaces_20of_20devices_1',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['initialization_2',['SCREEN mode initialization',['../group__SCREEN.html',1,'']]],
  ['initialspeed_3',['initialSpeed',['../group__SNDDRV__DATA.html#afeac8f9845a21b0c8dcb3fe9722c8b3f',1,'snd_Music']]],
  ['input_20device_4',['Input device',['../group__INPUT.html',1,'']]],
  ['input_20output_20system_5',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]],
  ['input_2eh_6',['input.h',['../input_8h.html',1,'']]],
  ['input_5fh_7',['INPUT_H',['../input_8h.html#a3124ba59577e5a4c41023f9360aa1458',1,'input.h']]],
  ['inspection_8',['Slot inspection',['../group__SLOT__INSPECT.html',1,'']]],
  ['install_20instructions_20of_20build_20tools_9',['Install instructions of Build tools',['../index.html#autotoc_md9',1,'']]],
  ['install_20other_20toolchain_10',['install other toolchain',['../index.html#autotoc_md12',1,'2. Install other toolchain'],['../index.html#autotoc_md16',1,'2. Install other toolchain']]],
  ['install_20sdcc_11',['install sdcc',['../index.html#autotoc_md11',1,'1. Install SDCC'],['../index.html#autotoc_md15',1,'1. Install SDCC']]],
  ['instructions_20of_20build_20tools_12',['Install instructions of Build tools',['../index.html#autotoc_md9',1,'']]],
  ['instructions_20of_20the_20library_20and_20sample_20projects_13',['Build instructions of the library and sample projects',['../index.html#autotoc_md17',1,'']]],
  ['instructions_20of_20user_20applications_14',['Build instructions of user applications',['../index.html#autotoc_md18',1,'']]],
  ['instrument_20timbre_20table_15',['Definition of Instrument (timbre) table',['../md_docs_2design-notes__snddrv__internal.html#autotoc_md50',1,'']]],
  ['instruments_16',['instruments',['../group__SNDDRV__DATA.html#a4c2b9c5d52e89f648ebd3d5df34b0a94',1,'snd_SoundAssets']]],
  ['inteface_17',['Joystick / Joypad inteface',['../group__INPUT__JOYPAD.html',1,'']]],
  ['integrate_20arkos_20tracker_202_20aks_20files_20into_20your_20application_18',['How to integrate Arkos Tracker 2 .aks files into your application',['../md_docs_2design-notes__snddrv.html#autotoc_md38',1,'']]],
  ['inter_20memory_20transfer_19',['inter memory transfer',['../group__XMEM__INTER__MEMORY__TRANSFER.html',1,'Building blocks for inter-memory transfer.'],['../group__XMEM.html',1,'XMEM - Inter-memory transfer.']]],
  ['inter_20memory_20transfer_20dedicated_20to_20banked_20memory_20access_20',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['inter_20memory_20transfer_20dedicated_20to_20rom_20ram_20access_21',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['inter_20memory_20transfer_20dedicated_20to_20vram_20access_22',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['inter_20slot_20read_20write_20call_23',['Inter-slot Read / Write / Call',['../group__BIOS__SLOT.html',1,'']]],
  ['interface_24',['interface',['../group__SPRITES__METASPRITE.html',1,'Meta-sprite interface.'],['../group__OPLL__DEVICE.html',1,'OPLL device interface'],['../group__SCC__DEVICE.html',1,'SCC/SCC+ device interface'],['../group__TTY__DEVICE.html',1,'Teletype/console device interface.'],['../group__VMEM__ACCESS.html',1,'VRAM access interface']]],
  ['interface_20for_20megarom_25',['Banked Memory interface for MegaROM.',['../group__BANKED__MEMORY.html',1,'']]],
  ['interface_20for_20rom_20ram_20megarom_26',['Stream interface for ROM / RAM / MegaROM.',['../group__STREAM.html',1,'']]],
  ['interface_20for_20the_20libmsx_20audio_20replayer_27',['The audio decoder interface for the libmsx audio replayer.',['../group__AUDIO__DECODER.html',1,'']]],
  ['internal_20of_20snddrv_28',['DESIGN NOTE : Internal of SNDDRV',['../md_docs_2design-notes__snddrv__internal.html',1,'']]],
  ['international_5fid_5f1_29',['INTERNATIONAL_ID_1',['../bios__const_8h.html#a91e2a52aaf73b50f909f12bb9f9fc9bc',1,'bios_const.h']]],
  ['international_5fid_5f2_30',['INTERNATIONAL_ID_2',['../bios__const_8h.html#a0c64be4c8a1cc67033892d7f4d83ac7a',1,'bios_const.h']]],
  ['interrupt_2eh_31',['interrupt.h',['../interrupt_8h.html',1,'']]],
  ['interrupt_5fh_32',['INTERRUPT_H',['../interrupt_8h.html#a3d22c5418c7671534ed2719747bc6b5d',1,'interrupt.h']]],
  ['interrupts_33',['interrupts',['../group__INTERRUPT__AWAIT.html',1,'Await interrupts'],['../group__INTERRUPT.html',1,'Interrupts']]],
  ['interrupts_20handler_34',['Interrupts handler',['../group__INTERRUPT__HANDLER.html',1,'']]],
  ['into_20your_20application_35',['How to integrate Arkos Tracker 2 .aks files into your application',['../md_docs_2design-notes__snddrv.html#autotoc_md38',1,'']]],
  ['io_2eh_36',['io.h',['../io_8h.html',1,'']]],
  ['io_5fh_37',['IO_H',['../io_8h.html#a7a88fe5b19b9d27c4d2b2d2501f8591a',1,'io.h']]],
  ['isloop_38',['isLoop',['../group__SNDDRV__DATA.html#a8235e7d4e853b68b722090b9f037394c',1,'snd_Music']]]
];
