var searchData=
[
  ['call_0',['Inter-slot Read / Write / Call',['../group__BIOS__SLOT.html',1,'']]],
  ['callback_20functions_20of_20the_20libmsx_20audio_20replayer_1',['Callback functions of the libmsx audio replayer.',['../group__AUDIO__CALLBACK.html',1,'']]],
  ['cartridge_2',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['characters_3',['Cursor position, Control characters.',['../group__CUI__CONTROL.html',1,'']]],
  ['check_20error_20status_20of_20the_20stream_4',['Check error status of the stream.',['../group__STREAM__ERR.html',1,'']]],
  ['chip_20buffer_20of_20the_20libmsx_20audio_20replayer_5',['Unified sound-chip buffer of the libmsx audio replayer.',['../group__AUDIO__BUFFER.html',1,'']]],
  ['color_20backdrop_20color_6',['Text color, Backdrop color',['../group__CUI__COLOR.html',1,'']]],
  ['color_20registers_7',['Color registers',['../group__VDP__COLOR__REGISTER.html',1,'']]],
  ['color_20table_8',['Sprite color table',['../group__SPRITES__COLOR.html',1,'']]],
  ['commands_20high_20level_20apis_9',['VDP commands (High level APIs)',['../group__VDP__COMMANDS__HIGH.html',1,'']]],
  ['commands_20low_20level_20apis_10',['VDP commands (Low level APIs)',['../group__VDP__COMMANDS__LOW.html',1,'']]],
  ['compression_11',['ZX0 data compression',['../group__ZX0.html',1,'']]],
  ['configuration_12',['System configuration',['../group__BIOS__CONFIG.html',1,'']]],
  ['console_20device_13',['Teletype/console device.',['../group__TTY.html',1,'']]],
  ['console_20device_20interface_14',['Teletype/console device interface.',['../group__TTY__DEVICE.html',1,'']]],
  ['control_20characters_15',['Cursor position, Control characters.',['../group__CUI__CONTROL.html',1,'']]],
  ['control_20registers_16',['Control registers',['../group__VDP__CONTROL__REGISTER.html',1,'']]],
  ['copying_20from_20banked_20memory_17',['Reading and copying from banked memory.',['../group__BANKED__MEMORY__INDIRECT__ACCESS.html',1,'']]],
  ['copying_20from_20resource_20in_20banked_20memory_18',['Reading and copying from resource in banked memory.',['../group__RESOURCES__INDIRECT__ACCESS.html',1,'']]],
  ['cpu_20mode_19',['Z80 / R800 CPU mode',['../group__BIOS__CPU.html',1,'']]],
  ['current_20position_20of_20the_20stream_20',['current position of the stream',['../group__STREAM__SEEK.html',1,'Get / Set the current position of the stream.'],['../group__STREAM__READ.html',1,'Read from the current position of the stream.']]],
  ['cursor_20position_20control_20characters_21',['Cursor position, Control characters.',['../group__CUI__CONTROL.html',1,'']]]
];
