var searchData=
[
  ['mapping_20for_208x8px_201bpp_20bitmap_20images_0',['Tile-mapping for 8x8px 1bpp bitmap images.',['../group__IM__TILEMAP__BM8x8.html',1,'']]],
  ['matrix_20transformation_20operators_20for_2016x16_201bpp_20sprite_20patterns_1',['Matrix transformation operators for 16x16 1bpp sprite patterns.',['../group__IM__TRANSFORM__SP16x16.html',1,'']]],
  ['matrix_20transformation_20operators_20for_208x8px_201bpp_20bitmap_20images_2',['Matrix transformation operators for 8x8px 1bpp bitmap images.',['../group__IM__TRANSFORM__BM8x8.html',1,'']]],
  ['megarom_3',['MegaROM',['../group__BANKED__MEMORY.html',1,'Banked Memory interface for MegaROM.'],['../group__STREAM.html',1,'Stream interface for ROM / RAM / MegaROM.']]],
  ['memory_4',['memory',['../group__RESOURCES__FIND.html',1,'Find a resource in banked memory.'],['../group__BANKED__MEMORY__INDIRECT__ACCESS.html',1,'Reading and copying from banked memory.'],['../group__RESOURCES__INDIRECT__ACCESS.html',1,'Reading and copying from resource in banked memory.']]],
  ['memory_20access_5',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['memory_20as_20a_20storage_20of_20named_20resources_6',['Banked Memory as a storage of Named Resources.',['../group__RESOURCES.html',1,'']]],
  ['memory_20by_20switching_20page_202_7',['Direct access to banked memory by switching page 2.',['../group__BANKED__MEMORY__DIRECT__ACCESS.html',1,'']]],
  ['memory_20interface_20for_20megarom_8',['Banked Memory interface for MegaROM.',['../group__BANKED__MEMORY.html',1,'']]],
  ['memory_20transfer_9',['memory transfer',['../group__XMEM__INTER__MEMORY__TRANSFER.html',1,'Building blocks for inter-memory transfer.'],['../group__XMEM.html',1,'XMEM - Inter-memory transfer.']]],
  ['memory_20transfer_20dedicated_20to_20banked_20memory_20access_10',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['memory_20transfer_20dedicated_20to_20rom_20ram_20access_11',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['memory_20transfer_20dedicated_20to_20vram_20access_12',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['meta_20sprite_20interface_13',['Meta-sprite interface.',['../group__SPRITES__METASPRITE.html',1,'']]],
  ['meta_20sprites_14',['Sprites / Meta-Sprites',['../group__SPRITES.html',1,'']]],
  ['mode_15',['mode',['../group__SCREEN__BITMAP.html',1,'Bitmap graphics mode'],['../group__SCREEN__TEXT.html',1,'TEXT mode'],['../group__SCREEN__PCG.html',1,'Tiled graphics mode'],['../group__BIOS__CPU.html',1,'Z80 / R800 CPU mode']]],
  ['mode_202_20animated_20color_20sprites_16',['SM2 (Sprite Mode 2) Animated Color Sprites.',['../group__SM2.html',1,'']]],
  ['mode_20initialization_17',['SCREEN mode initialization',['../group__SCREEN.html',1,'']]],
  ['mode_20registers_18',['Mode registers',['../group__VDP__MODE__REGISTER.html',1,'']]],
  ['module_19',['SM2 initialization for SM2 module.',['../group__SM2__INIT.html',1,'']]],
  ['msx_20music_20',['OPLL - YM2413 / MSX-MUSIC',['../group__OPLL.html',1,'']]],
  ['music_21',['OPLL - YM2413 / MSX-MUSIC',['../group__OPLL.html',1,'']]]
];
