var searchData=
[
  ['of_20building_20blocks_20for_20inter_20memory_20transfer_20dedicated_20to_20banked_20memory_20access_0',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['of_20building_20blocks_20for_20inter_20memory_20transfer_20dedicated_20to_20rom_20ram_20access_1',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['of_20building_20blocks_20for_20inter_20memory_20transfer_20dedicated_20to_20vram_20access_2',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['of_20devices_3',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['of_20interrupts_4',['State of interrupts',['../group__INTERRUPT__STATE.html',1,'']]],
  ['of_20named_20resources_5',['Banked Memory as a storage of Named Resources.',['../group__RESOURCES.html',1,'']]],
  ['of_20the_20libmsx_20audio_20replayer_6',['of the libmsx audio replayer',['../group__AUDIO__CALLBACK.html',1,'Callback functions of the libmsx audio replayer.'],['../group__AUDIO__REPLAYER.html',1,'The API of the libmsx audio replayer.'],['../group__AUDIO__BUFFER.html',1,'Unified sound-chip buffer of the libmsx audio replayer.']]],
  ['of_20the_20ndp_20sound_20driver_7',['The replayer APIs of the NDP sound driver.',['../group__NDP__REPLAYER.html',1,'']]],
  ['of_20the_20stream_8',['of the stream',['../group__STREAM__ERR.html',1,'Check error status of the stream.'],['../group__STREAM__SEEK.html',1,'Get / Set the current position of the stream.'],['../group__STREAM__READ.html',1,'Read from the current position of the stream.']]],
  ['old_20psg_20sound_20driver_9',['Sound - Old PSG sound driver',['../group__SOUND__OLD.html',1,'']]],
  ['old_20psg_20sound_20driver_20apis_10',['Old PSG sound driver APIs',['../group__SOUND__OLD__API.html',1,'']]],
  ['open_20la0_20file_20image_11',['Open LA0 file image.',['../group__LA0__OPEN.html',1,'']]],
  ['open_20ndp_20song_20data_20and_20set_20it_20in_20the_20driver_12',['Open NDP song data, and set it in the driver.',['../group__NDP__SONG.html',1,'']]],
  ['open_20stream_13',['Open stream.',['../group__STREAM__OPEN.html',1,'']]],
  ['operators_20for_2016x16_201bpp_20sprite_20patterns_14',['operators for 16x16 1bpp sprite patterns',['../group__IM__BOOLEAN__SP16x16.html',1,'Boolean operators for 16x16 1bpp sprite patterns.'],['../group__IM__TRANSFORM__SP16x16.html',1,'Matrix transformation operators for 16x16 1bpp sprite patterns.'],['../group__IM__SHIFT__SP16x16.html',1,'Shift operators for 16x16 1bpp sprite patterns.']]],
  ['operators_20for_208x8px_201bpp_20bitmap_20images_15',['operators for 8x8px 1bpp bitmap images',['../group__IM__BOOLEAN__BM8x8.html',1,'Boolean operators for 8x8px 1bpp bitmap images.'],['../group__IM__TRANSFORM__BM8x8.html',1,'Matrix transformation operators for 8x8px 1bpp bitmap images.'],['../group__IM__SHIFT__BM8x8.html',1,'Shift operators for 8x8px 1bpp bitmap images.']]],
  ['opll_20buffer_16',['OPLL Buffer',['../group__OPLL__BUFFER.html',1,'']]],
  ['opll_20device_20interface_17',['OPLL device interface',['../group__OPLL__DEVICE.html',1,'']]],
  ['opll_20sound_20driver_18',['LA0 - PSG, SCC/SCC+, OPLL sound driver.',['../group__LA0__DECODER.html',1,'']]],
  ['opll_20ym2413_20msx_20music_19',['OPLL - YM2413 / MSX-MUSIC',['../group__OPLL.html',1,'']]],
  ['other_20la0_20specific_20apis_20',['Other LA0 specific APIs.',['../group__LA0__MISC.html',1,'']]],
  ['output_21',['output',['../group__CUI.html',1,'Text output'],['../group__CUI__PRINT.html',1,'Text output']]],
  ['output_20system_22',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]]
];
