var searchData=
[
  ['backdrop_20color_0',['Text color, Backdrop color',['../group__CUI__COLOR.html',1,'']]],
  ['banked_20memory_1',['banked memory',['../group__RESOURCES__FIND.html',1,'Find a resource in banked memory.'],['../group__BANKED__MEMORY__INDIRECT__ACCESS.html',1,'Reading and copying from banked memory.'],['../group__RESOURCES__INDIRECT__ACCESS.html',1,'Reading and copying from resource in banked memory.']]],
  ['banked_20memory_20access_2',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['banked_20memory_20as_20a_20storage_20of_20named_20resources_3',['Banked Memory as a storage of Named Resources.',['../group__RESOURCES.html',1,'']]],
  ['banked_20memory_20by_20switching_20page_202_4',['Direct access to banked memory by switching page 2.',['../group__BANKED__MEMORY__DIRECT__ACCESS.html',1,'']]],
  ['banked_20memory_20interface_20for_20megarom_5',['Banked Memory interface for MegaROM.',['../group__BANKED__MEMORY.html',1,'']]],
  ['base_20address_20registers_6',['Table base address registers',['../group__VDP__TABLE__BASE__ADDRESS__REGISTER.html',1,'']]],
  ['basic_20input_20output_20system_7',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]],
  ['bios_20basic_20input_20output_20system_8',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]],
  ['bios_20interrupts_20slots_20etc_9',['BIOS, Interrupts, Slots, etc.',['../group__LIBMSX__SYS.html',1,'']]],
  ['bitmap_20graphics_20mode_10',['Bitmap graphics mode',['../group__SCREEN__BITMAP.html',1,'']]],
  ['bitmap_20image_20processing_11',['8x8px, 16x16px bitmap image processing.',['../group__IM.html',1,'']]],
  ['bitmap_20images_12',['bitmap images',['../group__IM__BOOLEAN__BM8x8.html',1,'Boolean operators for 8x8px 1bpp bitmap images.'],['../group__IM__TRANSFORM__BM8x8.html',1,'Matrix transformation operators for 8x8px 1bpp bitmap images.'],['../group__IM__SHIFT__BM8x8.html',1,'Shift operators for 8x8px 1bpp bitmap images.'],['../group__IM__TILEMAP__BM8x8.html',1,'Tile-mapping for 8x8px 1bpp bitmap images.']]],
  ['blocks_20for_20inter_20memory_20transfer_13',['Building blocks for inter-memory transfer.',['../group__XMEM__INTER__MEMORY__TRANSFER.html',1,'']]],
  ['blocks_20for_20inter_20memory_20transfer_20dedicated_20to_20banked_20memory_20access_14',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['blocks_20for_20inter_20memory_20transfer_20dedicated_20to_20rom_20ram_20access_15',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['blocks_20for_20inter_20memory_20transfer_20dedicated_20to_20vram_20access_16',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['boolean_20operators_20for_2016x16_201bpp_20sprite_20patterns_17',['Boolean operators for 16x16 1bpp sprite patterns.',['../group__IM__BOOLEAN__SP16x16.html',1,'']]],
  ['boolean_20operators_20for_208x8px_201bpp_20bitmap_20images_18',['Boolean operators for 8x8px 1bpp bitmap images.',['../group__IM__BOOLEAN__BM8x8.html',1,'']]],
  ['buffer_19',['Buffer',['../group__OPLL__BUFFER.html',1,'OPLL Buffer'],['../group__PSG__BUFFER.html',1,'PSG Buffer'],['../group__SCC__BUFFER.html',1,'SCC/SCC+ Buffer']]],
  ['buffer_20of_20the_20libmsx_20audio_20replayer_20',['Unified sound-chip buffer of the libmsx audio replayer.',['../group__AUDIO__BUFFER.html',1,'']]],
  ['building_20blocks_20for_20inter_20memory_20transfer_21',['Building blocks for inter-memory transfer.',['../group__XMEM__INTER__MEMORY__TRANSFER.html',1,'']]],
  ['building_20blocks_20for_20inter_20memory_20transfer_20dedicated_20to_20banked_20memory_20access_22',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['building_20blocks_20for_20inter_20memory_20transfer_20dedicated_20to_20rom_20ram_20access_23',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['building_20blocks_20for_20inter_20memory_20transfer_20dedicated_20to_20vram_20access_24',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['by_20switching_20page_202_25',['Direct access to banked memory by switching page 2.',['../group__BANKED__MEMORY__DIRECT__ACCESS.html',1,'']]]
];
