var searchData=
[
  ['scc_20scc_0',['Predefined waveforms for SCC/SCC+.',['../group__SCC__PREDEFINED__WAVEFORMS.html',1,'']]],
  ['scc_20scc_20buffer_1',['SCC/SCC+ Buffer',['../group__SCC__BUFFER.html',1,'']]],
  ['scc_20scc_20device_20interface_2',['SCC/SCC+ device interface',['../group__SCC__DEVICE.html',1,'']]],
  ['scc_20scc_20effector_3',['The &quot;PSG to SCC/SCC+&quot; effector.',['../group__AUDIO__EFX__PSG2SCC.html',1,'']]],
  ['scc_20scc_20sound_20cartridge_4',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['screen_20mode_20initialization_5',['SCREEN mode initialization',['../group__SCREEN.html',1,'']]],
  ['set_20the_20current_20position_20of_20the_20stream_6',['Get / Set the current position of the stream.',['../group__STREAM__SEEK.html',1,'']]],
  ['sleep_7',['Sleep',['../group__INTERRUPT__SLEEP.html',1,'']]],
  ['slot_20individual_20address_20spaces_20of_20devices_8',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['slot_20inspection_9',['Slot inspection',['../group__SLOT__INSPECT.html',1,'']]],
  ['slot_20read_20write_20call_10',['Inter-slot Read / Write / Call',['../group__BIOS__SLOT.html',1,'']]],
  ['snddrv_20apis_11',['SNDDRV APIs',['../group__SNDDRV__API.html',1,'']]],
  ['snddrv_20psg_20sound_20driver_12',['SNDDRV - PSG sound driver',['../group__SNDDRV.html',1,'']]],
  ['software_20envelope_20generator_20apis_13',['Software envelope generator APIs',['../group__SOUND__OLD__EG__API.html',1,'']]],
  ['sound_20cartridge_14',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['sound_20chip_20buffer_20of_20the_20libmsx_20audio_20replayer_15',['Unified sound-chip buffer of the libmsx audio replayer.',['../group__AUDIO__BUFFER.html',1,'']]],
  ['sound_20data_20structure_16',['Sound data structure',['../group__SNDDRV__DATA.html',1,'']]],
  ['sound_20driver_17',['SNDDRV - PSG sound driver',['../group__SNDDRV.html',1,'']]],
  ['sound_20driver_20apis_18',['Old PSG sound driver APIs',['../group__SOUND__OLD__API.html',1,'']]],
  ['sound_20generator_19',['PSG - AY-3-8910 / Programmable Sound Generator',['../group__PSG.html',1,'']]],
  ['sound_20old_20psg_20sound_20driver_20',['Sound - Old PSG sound driver',['../group__SOUND__OLD.html',1,'']]],
  ['spaces_20of_20devices_21',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['sprite_20attribute_20table_22',['Sprite attribute table',['../group__SPRITES__ATTR.html',1,'']]],
  ['sprite_20color_20table_23',['Sprite color table',['../group__SPRITES__COLOR.html',1,'']]],
  ['sprite_20interface_24',['Meta-sprite interface.',['../group__SPRITES__METASPRITE.html',1,'']]],
  ['sprites_20meta_20sprites_25',['Sprites / Meta-Sprites',['../group__SPRITES.html',1,'']]],
  ['status_20of_20the_20stream_26',['Check error status of the stream.',['../group__STREAM__ERR.html',1,'']]],
  ['status_20registers_27',['Status registers',['../group__VDP__STATUS__REGISTER.html',1,'']]],
  ['storage_20of_20named_20resources_28',['Banked Memory as a storage of Named Resources.',['../group__RESOURCES.html',1,'']]],
  ['stream_29',['stream',['../group__STREAM__ERR.html',1,'Check error status of the stream.'],['../group__STREAM__SEEK.html',1,'Get / Set the current position of the stream.'],['../group__STREAM__OPEN.html',1,'Open stream.'],['../group__STREAM__READ.html',1,'Read from the current position of the stream.']]],
  ['stream_20interface_20for_20rom_20ram_20megarom_30',['Stream interface for ROM / RAM / MegaROM.',['../group__STREAM.html',1,'']]],
  ['structure_31',['Sound data structure',['../group__SNDDRV__DATA.html',1,'']]],
  ['switching_20page_202_32',['Direct access to banked memory by switching page 2.',['../group__BANKED__MEMORY__DIRECT__ACCESS.html',1,'']]],
  ['system_33',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]],
  ['system_20configuration_34',['System configuration',['../group__BIOS__CONFIG.html',1,'']]]
];
