var searchData=
[
  ['scc_20scc_0',['Predefined waveforms for SCC/SCC+.',['../group__SCC__PREDEFINED__WAVEFORMS.html',1,'']]],
  ['scc_20scc_20buffer_1',['SCC/SCC+ Buffer',['../group__SCC__BUFFER.html',1,'']]],
  ['scc_20scc_20device_20interface_2',['SCC/SCC+ device interface',['../group__SCC__DEVICE.html',1,'']]],
  ['scc_20scc_20effector_3',['The &quot;PSG to SCC/SCC+&quot; effector.',['../group__AUDIO__EFX__PSG2SCC.html',1,'']]],
  ['scc_20scc_20opll_20sound_20driver_4',['LA0 - PSG, SCC/SCC+, OPLL sound driver.',['../group__LA0__DECODER.html',1,'']]],
  ['scc_20scc_20sound_20cartridge_5',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['screen_20mode_20initialization_6',['SCREEN mode initialization',['../group__SCREEN.html',1,'']]],
  ['set_20a_20song_20in_20la0_20file_20to_20the_20decoder_7',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['set_20the_20current_20position_20of_20the_20stream_8',['Get / Set the current position of the stream.',['../group__STREAM__SEEK.html',1,'']]],
  ['sleep_9',['Sleep',['../group__INTERRUPT__SLEEP.html',1,'']]],
  ['slot_20individual_20address_20spaces_20of_20devices_10',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['slot_20inspection_11',['Slot inspection',['../group__SLOT__INSPECT.html',1,'']]],
  ['slot_20read_20write_20call_12',['Inter-slot Read / Write / Call',['../group__BIOS__SLOT.html',1,'']]],
  ['snddrv_20apis_13',['SNDDRV APIs',['../group__SNDDRV__API.html',1,'']]],
  ['snddrv_20psg_20sound_20driver_14',['SNDDRV - PSG sound driver',['../group__SNDDRV.html',1,'']]],
  ['software_20envelope_20generator_20apis_15',['Software envelope generator APIs',['../group__SOUND__OLD__EG__API.html',1,'']]],
  ['song_20in_20la0_20file_20to_20the_20decoder_16',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['sound_20cartridge_17',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['sound_20chip_20buffer_20of_20the_20libmsx_20audio_20replayer_18',['Unified sound-chip buffer of the libmsx audio replayer.',['../group__AUDIO__BUFFER.html',1,'']]],
  ['sound_20data_20structure_19',['Sound data structure',['../group__SNDDRV__DATA.html',1,'']]],
  ['sound_20driver_20',['sound driver',['../group__LA0__DECODER.html',1,'LA0 - PSG, SCC/SCC+, OPLL sound driver.'],['../group__SNDDRV.html',1,'SNDDRV - PSG sound driver']]],
  ['sound_20driver_20apis_21',['Old PSG sound driver APIs',['../group__SOUND__OLD__API.html',1,'']]],
  ['sound_20generator_22',['PSG - AY-3-8910 / Programmable Sound Generator',['../group__PSG.html',1,'']]],
  ['sound_20old_20psg_20sound_20driver_23',['Sound - Old PSG sound driver',['../group__SOUND__OLD.html',1,'']]],
  ['spaces_20of_20devices_24',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['specific_20apis_25',['Other LA0 specific APIs.',['../group__LA0__MISC.html',1,'']]],
  ['sprite_20attribute_20table_26',['Sprite attribute table',['../group__SPRITES__ATTR.html',1,'']]],
  ['sprite_20color_20table_27',['Sprite color table',['../group__SPRITES__COLOR.html',1,'']]],
  ['sprite_20interface_28',['Meta-sprite interface.',['../group__SPRITES__METASPRITE.html',1,'']]],
  ['sprites_20meta_20sprites_29',['Sprites / Meta-Sprites',['../group__SPRITES.html',1,'']]],
  ['status_20of_20the_20stream_30',['Check error status of the stream.',['../group__STREAM__ERR.html',1,'']]],
  ['status_20registers_31',['Status registers',['../group__VDP__STATUS__REGISTER.html',1,'']]],
  ['storage_20of_20named_20resources_32',['Banked Memory as a storage of Named Resources.',['../group__RESOURCES.html',1,'']]],
  ['stream_33',['stream',['../group__STREAM__ERR.html',1,'Check error status of the stream.'],['../group__STREAM__SEEK.html',1,'Get / Set the current position of the stream.'],['../group__STREAM__OPEN.html',1,'Open stream.'],['../group__STREAM__READ.html',1,'Read from the current position of the stream.']]],
  ['stream_20interface_20for_20rom_20ram_20megarom_34',['Stream interface for ROM / RAM / MegaROM.',['../group__STREAM.html',1,'']]],
  ['structure_35',['Sound data structure',['../group__SNDDRV__DATA.html',1,'']]],
  ['switching_20page_202_36',['Direct access to banked memory by switching page 2.',['../group__BANKED__MEMORY__DIRECT__ACCESS.html',1,'']]],
  ['system_37',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]],
  ['system_20configuration_38',['System configuration',['../group__BIOS__CONFIG.html',1,'']]]
];
