var searchData=
[
  ['scc_0',['Predefined waveforms for SCC/SCC+.',['../group__SCC__PREDEFINED__WAVEFORMS.html',1,'']]],
  ['scc_20buffer_1',['SCC/SCC+ Buffer',['../group__SCC__BUFFER.html',1,'']]],
  ['scc_20device_20interface_2',['SCC/SCC+ device interface',['../group__SCC__DEVICE.html',1,'']]],
  ['scc_20effector_3',['The &quot;PSG to SCC/SCC+&quot; effector.',['../group__AUDIO__EFX__PSG2SCC.html',1,'']]],
  ['scc_20opll_20sound_20driver_4',['LA0 - PSG, SCC/SCC+, OPLL sound driver.',['../group__LA0__DECODER.html',1,'']]],
  ['scc_20scc_5',['Predefined waveforms for SCC/SCC+.',['../group__SCC__PREDEFINED__WAVEFORMS.html',1,'']]],
  ['scc_20scc_20buffer_6',['SCC/SCC+ Buffer',['../group__SCC__BUFFER.html',1,'']]],
  ['scc_20scc_20device_20interface_7',['SCC/SCC+ device interface',['../group__SCC__DEVICE.html',1,'']]],
  ['scc_20scc_20effector_8',['The &quot;PSG to SCC/SCC+&quot; effector.',['../group__AUDIO__EFX__PSG2SCC.html',1,'']]],
  ['scc_20scc_20opll_20sound_20driver_9',['LA0 - PSG, SCC/SCC+, OPLL sound driver.',['../group__LA0__DECODER.html',1,'']]],
  ['scc_20scc_20sound_20cartridge_10',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['scc_20sound_20cartridge_11',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['screen_20mode_20initialization_12',['SCREEN mode initialization',['../group__SCREEN.html',1,'']]],
  ['set_20a_20song_20in_20la0_20file_20to_20the_20decoder_13',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['set_20the_20current_20position_20of_20the_20stream_14',['Get / Set the current position of the stream.',['../group__STREAM__SEEK.html',1,'']]],
  ['shift_20operators_20for_2016x16_201bpp_20sprite_20patterns_15',['Shift operators for 16x16 1bpp sprite patterns.',['../group__IM__SHIFT__SP16x16.html',1,'']]],
  ['shift_20operators_20for_208x8px_201bpp_20bitmap_20images_16',['Shift operators for 8x8px 1bpp bitmap images.',['../group__IM__SHIFT__BM8x8.html',1,'']]],
  ['sleep_17',['Sleep',['../group__INTERRUPT__SLEEP.html',1,'']]],
  ['slot_20individual_20address_20spaces_20of_20devices_18',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['slot_20inspection_19',['Slot inspection',['../group__SLOT__INSPECT.html',1,'']]],
  ['slot_20read_20write_20call_20',['Inter-slot Read / Write / Call',['../group__BIOS__SLOT.html',1,'']]],
  ['snddrv_20apis_21',['SNDDRV APIs',['../group__SNDDRV__API.html',1,'']]],
  ['snddrv_20psg_20sound_20driver_22',['SNDDRV - PSG sound driver',['../group__SNDDRV.html',1,'']]],
  ['software_20envelope_20generator_20apis_23',['Software envelope generator APIs',['../group__SOUND__OLD__EG__API.html',1,'']]],
  ['song_20in_20la0_20file_20to_20the_20decoder_24',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['sound_20cartridge_25',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['sound_20chip_20buffer_20of_20the_20libmsx_20audio_20replayer_26',['Unified sound-chip buffer of the libmsx audio replayer.',['../group__AUDIO__BUFFER.html',1,'']]],
  ['sound_20data_20structure_27',['Sound data structure',['../group__SNDDRV__DATA.html',1,'']]],
  ['sound_20driver_28',['sound driver',['../group__LA0__DECODER.html',1,'LA0 - PSG, SCC/SCC+, OPLL sound driver.'],['../group__SNDDRV.html',1,'SNDDRV - PSG sound driver'],['../group__SOUND__OLD.html',1,'Sound - Old PSG sound driver']]],
  ['sound_20driver_20apis_29',['Old PSG sound driver APIs',['../group__SOUND__OLD__API.html',1,'']]],
  ['sound_20generator_30',['PSG - AY-3-8910 / Programmable Sound Generator',['../group__PSG.html',1,'']]],
  ['sound_20old_20psg_20sound_20driver_31',['Sound - Old PSG sound driver',['../group__SOUND__OLD.html',1,'']]],
  ['spaces_20of_20devices_32',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['specific_20apis_33',['Other LA0 specific APIs.',['../group__LA0__MISC.html',1,'']]],
  ['sprite_20attribute_20table_34',['Sprite attribute table',['../group__SPRITES__ATTR.html',1,'']]],
  ['sprite_20color_20table_35',['Sprite color table',['../group__SPRITES__COLOR.html',1,'']]],
  ['sprite_20interface_36',['Meta-sprite interface.',['../group__SPRITES__METASPRITE.html',1,'']]],
  ['sprite_20patterns_37',['sprite patterns',['../group__IM__BOOLEAN__SP16x16.html',1,'Boolean operators for 16x16 1bpp sprite patterns.'],['../group__IM__TRANSFORM__SP16x16.html',1,'Matrix transformation operators for 16x16 1bpp sprite patterns.'],['../group__IM__SHIFT__SP16x16.html',1,'Shift operators for 16x16 1bpp sprite patterns.'],['../group__IM__TRIM__SP16x16.html',1,'Trimming (Cropping) for 16x16 1bpp sprite patterns.']]],
  ['sprites_38',['Sprites / Meta-Sprites',['../group__SPRITES.html',1,'']]],
  ['sprites_20meta_20sprites_39',['Sprites / Meta-Sprites',['../group__SPRITES.html',1,'']]],
  ['state_20of_20interrupts_40',['State of interrupts',['../group__INTERRUPT__STATE.html',1,'']]],
  ['status_20of_20the_20stream_41',['Check error status of the stream.',['../group__STREAM__ERR.html',1,'']]],
  ['status_20registers_42',['Status registers',['../group__VDP__STATUS__REGISTER.html',1,'']]],
  ['storage_20of_20named_20resources_43',['Banked Memory as a storage of Named Resources.',['../group__RESOURCES.html',1,'']]],
  ['stream_44',['stream',['../group__STREAM__ERR.html',1,'Check error status of the stream.'],['../group__STREAM__SEEK.html',1,'Get / Set the current position of the stream.'],['../group__STREAM__OPEN.html',1,'Open stream.'],['../group__STREAM__READ.html',1,'Read from the current position of the stream.']]],
  ['stream_20interface_20for_20rom_20ram_20megarom_45',['Stream interface for ROM / RAM / MegaROM.',['../group__STREAM.html',1,'']]],
  ['structure_46',['Sound data structure',['../group__SNDDRV__DATA.html',1,'']]],
  ['switching_20page_202_47',['Direct access to banked memory by switching page 2.',['../group__BANKED__MEMORY__DIRECT__ACCESS.html',1,'']]],
  ['system_48',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]],
  ['system_20configuration_49',['System configuration',['../group__BIOS__CONFIG.html',1,'']]]
];
