var searchData=
[
  ['data_20and_20set_20it_20in_20the_20driver_0',['data and set it in the driver',['../group__NDP__SONG.html',1,'Open NDP song data, and set it in the driver.'],['../group__NDP__SFX.html',1,'Open NDS sound effects data, and set it in the driver.']]],
  ['data_20compression_1',['ZX0 data compression',['../group__ZX0.html',1,'']]],
  ['data_20structure_2',['Sound data structure',['../group__SNDDRV__DATA.html',1,'']]],
  ['data_20types_3',['SM2 Data Types',['../group__SM2__DATATYPES.html',1,'']]],
  ['decoder_4',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['decoder_20interface_20for_20the_20libmsx_20audio_20replayer_5',['The audio decoder interface for the libmsx audio replayer.',['../group__AUDIO__DECODER.html',1,'']]],
  ['decompression_6',['Compression / Decompression.',['../group__LIBMSX__COMPRESS.html',1,'']]],
  ['decompressor_7',['ZX0 decompressor.',['../group__ZX0__DECOMPRESS.html',1,'']]],
  ['dedicated_20to_20banked_20memory_20access_8',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['dedicated_20to_20rom_20ram_20access_9',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['dedicated_20to_20vram_20access_10',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['device_11',['Human Interaction Device.',['../group__LIBMSX__HID.html',1,'']]],
  ['device_12',['device',['../group__INPUT.html',1,'Input device'],['../group__TTY.html',1,'Teletype/console device.']]],
  ['device_20interface_13',['device interface',['../group__OPLL__DEVICE.html',1,'OPLL device interface'],['../group__SCC__DEVICE.html',1,'SCC/SCC+ device interface'],['../group__TTY__DEVICE.html',1,'Teletype/console device interface.']]],
  ['devices_14',['devices',['../group__SLOT.html',1,'Slot - Individual Address Spaces of devices.'],['../group__LIBMSX__SOUNDCHIP.html',1,'Sound devices.']]],
  ['direct_20access_20to_20banked_20memory_20by_20switching_20page_202_15',['Direct access to banked memory by switching page 2.',['../group__BANKED__MEMORY__DIRECT__ACCESS.html',1,'']]],
  ['display_20animated_20color_20sprites_16',['SM2 display Animated Color Sprites.',['../group__SM2__DISPLAY.html',1,'']]],
  ['display_20graphics_17',['Video / Display / Graphics.',['../group__LIBMSX__GRAPHICS.html',1,'']]],
  ['display_20processor_18',['VDP - Video Display Processor',['../group__VDP.html',1,'']]],
  ['display_20registers_19',['Display registers',['../group__VDP__DISPLAY__REGISTER.html',1,'']]],
  ['driver_20',['driver',['../group__LA0__DECODER.html',1,'LA0 - PSG, SCC/SCC+, OPLL sound driver.'],['../group__NDP.html',1,'NDP - NDP sound driver.'],['../group__NDP__SONG.html',1,'Open NDP song data, and set it in the driver.'],['../group__NDP__SFX.html',1,'Open NDS sound effects data, and set it in the driver.'],['../group__SNDDRV.html',1,'SNDDRV - PSG sound driver'],['../group__SOUND__OLD.html',1,'Sound - Old PSG sound driver'],['../group__NDP__REPLAYER.html',1,'The replayer APIs of the NDP sound driver.']]],
  ['driver_20apis_21',['Old PSG sound driver APIs',['../group__SOUND__OLD__API.html',1,'']]],
  ['drivers_20replayers_22',['Sound drivers / replayers.',['../group__LIBMSX__REPLAYER.html',1,'']]]
];
