var searchData=
[
  ['image_0',['Open LA0 file image.',['../group__LA0__OPEN.html',1,'']]],
  ['image_20processing_1',['8x8px, 16x16px bitmap image processing.',['../group__IM.html',1,'']]],
  ['images_2',['images',['../group__IM__BOOLEAN__BM8x8.html',1,'Boolean operators for 8x8px 1bpp bitmap images.'],['../group__IM__TRANSFORM__BM8x8.html',1,'Matrix transformation operators for 8x8px 1bpp bitmap images.'],['../group__IM__SHIFT__BM8x8.html',1,'Shift operators for 8x8px 1bpp bitmap images.'],['../group__IM__TILEMAP__BM8x8.html',1,'Tile-mapping for 8x8px 1bpp bitmap images.']]],
  ['in_20banked_20memory_3',['in banked memory',['../group__RESOURCES__FIND.html',1,'Find a resource in banked memory.'],['../group__RESOURCES__INDIRECT__ACCESS.html',1,'Reading and copying from resource in banked memory.']]],
  ['in_20la0_20file_20to_20the_20decoder_4',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['individual_20address_20spaces_20of_20devices_5',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['initialization_6',['SCREEN mode initialization',['../group__SCREEN.html',1,'']]],
  ['input_20device_7',['Input device',['../group__INPUT.html',1,'']]],
  ['input_20output_20system_8',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]],
  ['inspection_9',['Slot inspection',['../group__SLOT__INSPECT.html',1,'']]],
  ['inteface_10',['Joystick / Joypad inteface',['../group__INPUT__JOYPAD.html',1,'']]],
  ['inter_20memory_20transfer_11',['inter memory transfer',['../group__XMEM__INTER__MEMORY__TRANSFER.html',1,'Building blocks for inter-memory transfer.'],['../group__XMEM.html',1,'XMEM - Inter-memory transfer.']]],
  ['inter_20memory_20transfer_20dedicated_20to_20banked_20memory_20access_12',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['inter_20memory_20transfer_20dedicated_20to_20rom_20ram_20access_13',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['inter_20memory_20transfer_20dedicated_20to_20vram_20access_14',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['inter_20slot_20read_20write_20call_15',['Inter-slot Read / Write / Call',['../group__BIOS__SLOT.html',1,'']]],
  ['interface_16',['interface',['../group__SPRITES__METASPRITE.html',1,'Meta-sprite interface.'],['../group__OPLL__DEVICE.html',1,'OPLL device interface'],['../group__SCC__DEVICE.html',1,'SCC/SCC+ device interface'],['../group__TTY__DEVICE.html',1,'Teletype/console device interface.'],['../group__VMEM__ACCESS.html',1,'VRAM access interface']]],
  ['interface_20for_20megarom_17',['Banked Memory interface for MegaROM.',['../group__BANKED__MEMORY.html',1,'']]],
  ['interface_20for_20rom_20ram_20megarom_18',['Stream interface for ROM / RAM / MegaROM.',['../group__STREAM.html',1,'']]],
  ['interface_20for_20the_20libmsx_20audio_20replayer_19',['The audio decoder interface for the libmsx audio replayer.',['../group__AUDIO__DECODER.html',1,'']]],
  ['interrupts_20',['interrupts',['../group__INTERRUPT__AWAIT.html',1,'Await interrupts'],['../group__INTERRUPT.html',1,'Interrupts']]],
  ['interrupts_20handler_21',['Interrupts handler',['../group__INTERRUPT__HANDLER.html',1,'']]]
];
