var searchData=
[
  ['image_0',['Open LA0 file image.',['../group__LA0__OPEN.html',1,'']]],
  ['image_20processing_1',['Image processing.',['../group__LIBMSX__IMAGE__PROC.html',1,'']]],
  ['image_20processing_2',['8x8px, 16x16px bitmap image processing.',['../group__IM.html',1,'']]],
  ['images_3',['images',['../group__IM__BOOLEAN__BM8x8.html',1,'Boolean operators for 8x8px 1bpp bitmap images.'],['../group__IM__TRANSFORM__BM8x8.html',1,'Matrix transformation operators for 8x8px 1bpp bitmap images.'],['../group__IM__SHIFT__BM8x8.html',1,'Shift operators for 8x8px 1bpp bitmap images.'],['../group__IM__TILEMAP__BM8x8.html',1,'Tile-mapping for 8x8px 1bpp bitmap images.']]],
  ['in_20banked_20memory_4',['in banked memory',['../group__RESOURCES__FIND.html',1,'Find a resource in banked memory.'],['../group__RESOURCES__INDIRECT__ACCESS.html',1,'Reading and copying from resource in banked memory.']]],
  ['in_20la0_20file_20to_20the_20decoder_5',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['individual_20address_20spaces_20of_20devices_6',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['initialization_7',['SCREEN mode initialization',['../group__SCREEN.html',1,'']]],
  ['initialization_20for_20sm2_20module_8',['SM2 initialization for SM2 module.',['../group__SM2__INIT.html',1,'']]],
  ['input_20device_9',['Input device',['../group__INPUT.html',1,'']]],
  ['input_20output_20system_10',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]],
  ['inspection_11',['Slot inspection',['../group__SLOT__INSPECT.html',1,'']]],
  ['inteface_12',['Joystick / Joypad inteface',['../group__INPUT__JOYPAD.html',1,'']]],
  ['inter_20memory_20transfer_13',['XMEM - Inter-memory transfer.',['../group__XMEM.html',1,'']]],
  ['inter_20memory_20transfer_14',['Building blocks for inter-memory transfer.',['../group__XMEM__INTER__MEMORY__TRANSFER.html',1,'']]],
  ['inter_20memory_20transfer_20dedicated_20to_20banked_20memory_20access_15',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['inter_20memory_20transfer_20dedicated_20to_20rom_20ram_20access_16',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['inter_20memory_20transfer_20dedicated_20to_20vram_20access_17',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['inter_20slot_20read_20write_20call_18',['Inter-slot Read / Write / Call',['../group__BIOS__SLOT.html',1,'']]],
  ['interaction_20device_19',['Human Interaction Device.',['../group__LIBMSX__HID.html',1,'']]],
  ['interface_20',['Interface',['../group__LIBMSX__CUI.html',1,'Character User Interface.'],['../group__LIBMSX__STORAGE.html',1,'RAM/ROM/MegaROM Storage Interface.']]],
  ['interface_21',['interface',['../group__SPRITES__METASPRITE.html',1,'Meta-sprite interface.'],['../group__OPLL__DEVICE.html',1,'OPLL device interface'],['../group__SCC__DEVICE.html',1,'SCC/SCC+ device interface'],['../group__TTY__DEVICE.html',1,'Teletype/console device interface.'],['../group__VMEM__ACCESS.html',1,'VRAM access interface']]],
  ['interface_20for_20megarom_22',['Banked Memory interface for MegaROM.',['../group__BANKED__MEMORY.html',1,'']]],
  ['interface_20for_20rom_20ram_20megarom_23',['Stream interface for ROM / RAM / MegaROM.',['../group__STREAM.html',1,'']]],
  ['interface_20for_20the_20libmsx_20audio_20replayer_24',['The audio decoder interface for the libmsx audio replayer.',['../group__AUDIO__DECODER.html',1,'']]],
  ['interrupts_25',['Interrupts',['../group__INTERRUPT.html',1,'']]],
  ['interrupts_26',['interrupts',['../group__INTERRUPT__AWAIT.html',1,'Await interrupts'],['../group__INTERRUPT__STATE.html',1,'State of interrupts']]],
  ['interrupts_20handler_27',['Interrupts handler',['../group__INTERRUPT__HANDLER.html',1,'']]],
  ['interrupts_20slots_20etc_28',['BIOS, Interrupts, Slots, etc.',['../group__LIBMSX__SYS.html',1,'']]]
];
