var searchData=
[
  ['scc_0',['Predefined waveforms for SCC/SCC+.',['../group__SCC__PREDEFINED__WAVEFORMS.html',1,'']]],
  ['scc_20buffer_1',['SCC/SCC+ Buffer',['../group__SCC__BUFFER.html',1,'']]],
  ['scc_20device_20interface_2',['SCC/SCC+ device interface',['../group__SCC__DEVICE.html',1,'']]],
  ['scc_20effector_3',['The &quot;PSG to SCC/SCC+&quot; effector.',['../group__AUDIO__EFX__PSG2SCC.html',1,'']]],
  ['scc_20opll_20sound_20driver_4',['LA0 - PSG, SCC/SCC+, OPLL sound driver.',['../group__LA0__DECODER.html',1,'']]],
  ['scc_20scc_5',['Predefined waveforms for SCC/SCC+.',['../group__SCC__PREDEFINED__WAVEFORMS.html',1,'']]],
  ['scc_20scc_20buffer_6',['SCC/SCC+ Buffer',['../group__SCC__BUFFER.html',1,'']]],
  ['scc_20scc_20device_20interface_7',['SCC/SCC+ device interface',['../group__SCC__DEVICE.html',1,'']]],
  ['scc_20scc_20effector_8',['The &quot;PSG to SCC/SCC+&quot; effector.',['../group__AUDIO__EFX__PSG2SCC.html',1,'']]],
  ['scc_20scc_20opll_20sound_20driver_9',['LA0 - PSG, SCC/SCC+, OPLL sound driver.',['../group__LA0__DECODER.html',1,'']]],
  ['scc_20scc_20sound_20cartridge_10',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['scc_20sound_20cartridge_11',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['screen_20mode_20initialization_12',['SCREEN mode initialization',['../group__SCREEN.html',1,'']]],
  ['set_20a_20song_20in_20la0_20file_20to_20the_20decoder_13',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['set_20it_20in_20the_20driver_14',['Open NDP song data, and set it in the driver.',['../group__NDP__SONG.html',1,'']]],
  ['set_20the_20current_20position_20of_20the_20stream_15',['Get / Set the current position of the stream.',['../group__STREAM__SEEK.html',1,'']]],
  ['shift_20operators_20for_2016x16_201bpp_20sprite_20patterns_16',['Shift operators for 16x16 1bpp sprite patterns.',['../group__IM__SHIFT__SP16x16.html',1,'']]],
  ['shift_20operators_20for_208x8px_201bpp_20bitmap_20images_17',['Shift operators for 8x8px 1bpp bitmap images.',['../group__IM__SHIFT__BM8x8.html',1,'']]],
  ['sleep_18',['Sleep',['../group__INTERRUPT__SLEEP.html',1,'']]],
  ['slot_20individual_20address_20spaces_20of_20devices_19',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['slot_20inspection_20',['Slot inspection',['../group__SLOT__INSPECT.html',1,'']]],
  ['slot_20read_20write_20call_21',['Inter-slot Read / Write / Call',['../group__BIOS__SLOT.html',1,'']]],
  ['slots_20etc_22',['BIOS, Interrupts, Slots, etc.',['../group__LIBMSX__SYS.html',1,'']]],
  ['sm2_20data_20types_23',['SM2 Data Types',['../group__SM2__DATATYPES.html',1,'']]],
  ['sm2_20display_20animated_20color_20sprites_24',['SM2 display Animated Color Sprites.',['../group__SM2__DISPLAY.html',1,'']]],
  ['sm2_20initialization_20for_20sm2_20module_25',['SM2 initialization for SM2 module.',['../group__SM2__INIT.html',1,'']]],
  ['sm2_20module_26',['SM2 initialization for SM2 module.',['../group__SM2__INIT.html',1,'']]],
  ['sm2_20sprite_20mode_202_20animated_20color_20sprites_27',['SM2 (Sprite Mode 2) Animated Color Sprites.',['../group__SM2.html',1,'']]],
  ['sm2_20updates_20animation_20state_28',['SM2 updates animation state.',['../group__SM2__ANIMATION.html',1,'']]],
  ['snddrv_20apis_29',['SNDDRV APIs',['../group__SNDDRV__API.html',1,'']]],
  ['snddrv_20psg_20sound_20driver_30',['SNDDRV - PSG sound driver',['../group__SNDDRV.html',1,'']]],
  ['software_20envelope_20generator_20apis_31',['Software envelope generator APIs',['../group__SOUND__OLD__EG__API.html',1,'']]],
  ['song_20data_20and_20set_20it_20in_20the_20driver_32',['Open NDP song data, and set it in the driver.',['../group__NDP__SONG.html',1,'']]],
  ['song_20in_20la0_20file_20to_20the_20decoder_33',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['sound_20cartridge_34',['Konami SCC/SCC+ sound cartridge',['../group__SCC.html',1,'']]],
  ['sound_20chip_20buffer_20of_20the_20libmsx_20audio_20replayer_35',['Unified sound-chip buffer of the libmsx audio replayer.',['../group__AUDIO__BUFFER.html',1,'']]],
  ['sound_20data_20structure_36',['Sound data structure',['../group__SNDDRV__DATA.html',1,'']]],
  ['sound_20devices_37',['Sound devices.',['../group__LIBMSX__SOUNDCHIP.html',1,'']]],
  ['sound_20driver_38',['sound driver',['../group__LA0__DECODER.html',1,'LA0 - PSG, SCC/SCC+, OPLL sound driver.'],['../group__NDP.html',1,'NDP - NDP sound driver.'],['../group__SNDDRV.html',1,'SNDDRV - PSG sound driver'],['../group__SOUND__OLD.html',1,'Sound - Old PSG sound driver'],['../group__NDP__REPLAYER.html',1,'The replayer APIs of the NDP sound driver.']]],
  ['sound_20driver_20apis_39',['Old PSG sound driver APIs',['../group__SOUND__OLD__API.html',1,'']]],
  ['sound_20drivers_40',['Audio/Sound drivers.',['../group__LIBMSX__REPLAYER.html',1,'']]],
  ['sound_20generator_41',['PSG - AY-3-8910 / Programmable Sound Generator',['../group__PSG.html',1,'']]],
  ['sound_20old_20psg_20sound_20driver_42',['Sound - Old PSG sound driver',['../group__SOUND__OLD.html',1,'']]],
  ['spaces_20of_20devices_43',['Slot - Individual Address Spaces of devices.',['../group__SLOT.html',1,'']]],
  ['specific_20apis_44',['Other LA0 specific APIs.',['../group__LA0__MISC.html',1,'']]],
  ['sprite_20attribute_20table_45',['Sprite attribute table',['../group__SPRITES__ATTR.html',1,'']]],
  ['sprite_20color_20table_46',['Sprite color table',['../group__SPRITES__COLOR.html',1,'']]],
  ['sprite_20interface_47',['Meta-sprite interface.',['../group__SPRITES__METASPRITE.html',1,'']]],
  ['sprite_20mode_202_20animated_20color_20sprites_48',['SM2 (Sprite Mode 2) Animated Color Sprites.',['../group__SM2.html',1,'']]],
  ['sprite_20patterns_49',['sprite patterns',['../group__IM__BOOLEAN__SP16x16.html',1,'Boolean operators for 16x16 1bpp sprite patterns.'],['../group__IM__TRANSFORM__SP16x16.html',1,'Matrix transformation operators for 16x16 1bpp sprite patterns.'],['../group__IM__SHIFT__SP16x16.html',1,'Shift operators for 16x16 1bpp sprite patterns.'],['../group__IM__TRIM__SP16x16.html',1,'Trimming (Cropping) for 16x16 1bpp sprite patterns.']]],
  ['sprites_50',['Sprites',['../group__SM2.html',1,'SM2 (Sprite Mode 2) Animated Color Sprites.'],['../group__SM2__DISPLAY.html',1,'SM2 display Animated Color Sprites.'],['../group__SPRITES.html',1,'Sprites / Meta-Sprites']]],
  ['sprites_20meta_20sprites_51',['Sprites / Meta-Sprites',['../group__SPRITES.html',1,'']]],
  ['state_52',['SM2 updates animation state.',['../group__SM2__ANIMATION.html',1,'']]],
  ['state_20of_20interrupts_53',['State of interrupts',['../group__INTERRUPT__STATE.html',1,'']]],
  ['status_20of_20the_20stream_54',['Check error status of the stream.',['../group__STREAM__ERR.html',1,'']]],
  ['status_20registers_55',['Status registers',['../group__VDP__STATUS__REGISTER.html',1,'']]],
  ['storage_20interface_56',['RAM/ROM/MegaROM Storage Interface.',['../group__LIBMSX__STORAGE.html',1,'']]],
  ['storage_20of_20named_20resources_57',['Banked Memory as a storage of Named Resources.',['../group__RESOURCES.html',1,'']]],
  ['stream_58',['stream',['../group__STREAM__ERR.html',1,'Check error status of the stream.'],['../group__STREAM__SEEK.html',1,'Get / Set the current position of the stream.'],['../group__STREAM__OPEN.html',1,'Open stream.'],['../group__STREAM__READ.html',1,'Read from the current position of the stream.']]],
  ['stream_20interface_20for_20rom_20ram_20megarom_59',['Stream interface for ROM / RAM / MegaROM.',['../group__STREAM.html',1,'']]],
  ['structure_60',['Sound data structure',['../group__SNDDRV__DATA.html',1,'']]],
  ['switching_20page_202_61',['Direct access to banked memory by switching page 2.',['../group__BANKED__MEMORY__DIRECT__ACCESS.html',1,'']]],
  ['system_62',['BIOS - Basic Input/Output System',['../group__BIOS.html',1,'']]],
  ['system_20configuration_63',['System configuration',['../group__BIOS__CONFIG.html',1,'']]]
];
