var searchData=
[
  ['table_0',['table',['../group__SPRITES__ATTR.html',1,'Sprite attribute table'],['../group__SPRITES__COLOR.html',1,'Sprite color table']]],
  ['table_20base_20address_20registers_1',['Table base address registers',['../group__VDP__TABLE__BASE__ADDRESS__REGISTER.html',1,'']]],
  ['teletype_20console_20device_2',['Teletype/console device.',['../group__TTY.html',1,'']]],
  ['teletype_20console_20device_20interface_3',['Teletype/console device interface.',['../group__TTY__DEVICE.html',1,'']]],
  ['text_20color_20backdrop_20color_4',['Text color, Backdrop color',['../group__CUI__COLOR.html',1,'']]],
  ['text_20mode_5',['TEXT mode',['../group__SCREEN__TEXT.html',1,'']]],
  ['text_20output_6',['Text output',['../group__CUI.html',1,'Text output'],['../group__CUI__PRINT.html',1,'Text output']]],
  ['the_20amp_20effector_7',['The AMP effector.',['../group__AUDIO__EFX__AMP.html',1,'']]],
  ['the_20api_20of_20the_20libmsx_20audio_20replayer_8',['The API of the libmsx audio replayer.',['../group__AUDIO__REPLAYER.html',1,'']]],
  ['the_20audio_20decoder_20interface_20for_20the_20libmsx_20audio_20replayer_9',['The audio decoder interface for the libmsx audio replayer.',['../group__AUDIO__DECODER.html',1,'']]],
  ['the_20current_20position_20of_20the_20stream_10',['the current position of the stream',['../group__STREAM__SEEK.html',1,'Get / Set the current position of the stream.'],['../group__STREAM__READ.html',1,'Read from the current position of the stream.']]],
  ['the_20decoder_11',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['the_20libmsx_20audio_20replayer_12',['The libmsx audio replayer.',['../group__AUDIO.html',1,'']]],
  ['the_20libmsx_20audio_20replayer_13',['the libmsx audio replayer',['../group__AUDIO__CALLBACK.html',1,'Callback functions of the libmsx audio replayer.'],['../group__AUDIO__DECODERS.html',1,'Decoders for the libmsx audio replayer.'],['../group__AUDIO__EFX.html',1,'Effectors for the libmsx audio replayer.'],['../group__AUDIO__REPLAYER.html',1,'The API of the libmsx audio replayer.'],['../group__AUDIO__DECODER.html',1,'The audio decoder interface for the libmsx audio replayer.'],['../group__AUDIO__BUFFER.html',1,'Unified sound-chip buffer of the libmsx audio replayer.']]],
  ['the_20psg_20to_20scc_20scc_20effector_14',['The &quot;PSG to SCC/SCC+&quot; effector.',['../group__AUDIO__EFX__PSG2SCC.html',1,'']]],
  ['the_20stream_15',['the stream',['../group__STREAM__ERR.html',1,'Check error status of the stream.'],['../group__STREAM__SEEK.html',1,'Get / Set the current position of the stream.'],['../group__STREAM__READ.html',1,'Read from the current position of the stream.']]],
  ['tile_20mapping_20for_208x8px_201bpp_20bitmap_20images_16',['Tile-mapping for 8x8px 1bpp bitmap images.',['../group__IM__TILEMAP__BM8x8.html',1,'']]],
  ['tiled_20graphics_20mode_17',['Tiled graphics mode',['../group__SCREEN__PCG.html',1,'']]],
  ['to_20banked_20memory_20access_18',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['to_20banked_20memory_20by_20switching_20page_202_19',['Direct access to banked memory by switching page 2.',['../group__BANKED__MEMORY__DIRECT__ACCESS.html',1,'']]],
  ['to_20rom_20ram_20access_20',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['to_20scc_20scc_20effector_21',['The &quot;PSG to SCC/SCC+&quot; effector.',['../group__AUDIO__EFX__PSG2SCC.html',1,'']]],
  ['to_20the_20decoder_22',['Set a song in LA0 file to the decoder.',['../group__LA0__SET__SONG.html',1,'']]],
  ['to_20vram_20access_23',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['transfer_24',['transfer',['../group__XMEM__INTER__MEMORY__TRANSFER.html',1,'Building blocks for inter-memory transfer.'],['../group__XMEM.html',1,'XMEM - Inter-memory transfer.']]],
  ['transfer_20dedicated_20to_20banked_20memory_20access_25',['A part of building blocks for inter-memory transfer, dedicated to Banked Memory access.',['../group__BMEM__RD.html',1,'']]],
  ['transfer_20dedicated_20to_20rom_20ram_20access_26',['A part of building blocks for inter-memory transfer, dedicated to ROM / RAM access.',['../group__MEM__RW.html',1,'']]],
  ['transfer_20dedicated_20to_20vram_20access_27',['A part of building blocks for inter-memory transfer, dedicated to VRAM access.',['../group__VMEM__RW.html',1,'']]],
  ['transformation_20operators_20for_2016x16_201bpp_20sprite_20patterns_28',['Matrix transformation operators for 16x16 1bpp sprite patterns.',['../group__IM__TRANSFORM__SP16x16.html',1,'']]],
  ['transformation_20operators_20for_208x8px_201bpp_20bitmap_20images_29',['Matrix transformation operators for 8x8px 1bpp bitmap images.',['../group__IM__TRANSFORM__BM8x8.html',1,'']]],
  ['trimming_20cropping_20for_2016x16_201bpp_20sprite_20patterns_30',['Trimming (Cropping) for 16x16 1bpp sprite patterns.',['../group__IM__TRIM__SP16x16.html',1,'']]]
];
