// Code generated by ase2msx TJ_dog.ase; DO NOT EDIT.
#include "TJ_dog.h"

#define LEN(a) (sizeof(a)/sizeof(a[0]))
#define CELS_MAX (9)

static sm2_Cel cels[CELS_MAX];
static const uint8_t frame_0_cel_ids[] = {0,};
static const uint8_t frame_1_cel_ids[] = {3,};
static const uint8_t frame_2_cel_ids[] = {6,};
static const uint8_t frame_3_cel_ids[] = {1,};
static const uint8_t frame_4_cel_ids[] = {4,};
static const uint8_t frame_5_cel_ids[] = {7,};
static const uint8_t frame_6_cel_ids[] = {2,};
static const uint8_t frame_7_cel_ids[] = {5,};
static const uint8_t frame_8_cel_ids[] = {8,};
static const sm2_Frame frames[] = {
  {.duration = 100, .cel_ids = SM2_SLICE(frame_0_cel_ids), },
  {.duration = 100, .cel_ids = SM2_SLICE(frame_1_cel_ids), },
  {.duration = 100, .cel_ids = SM2_SLICE(frame_2_cel_ids), },
  {.duration = 100, .cel_ids = SM2_SLICE(frame_3_cel_ids), },
  {.duration = 100, .cel_ids = SM2_SLICE(frame_4_cel_ids), },
  {.duration = 100, .cel_ids = SM2_SLICE(frame_5_cel_ids), },
  {.duration = 100, .cel_ids = SM2_SLICE(frame_6_cel_ids), },
  {.duration = 100, .cel_ids = SM2_SLICE(frame_7_cel_ids), },
  {.duration = 100, .cel_ids = SM2_SLICE(frame_8_cel_ids), },
};

const sm2_SpriteSheet TJ_dog = {
  .frames = SM2_SLICE(frames),
  .cels = SM2_SLICE(cels),
};
const sm2_FrameTag TJ_dog_tag_Walk = {.from = 0, .to = 8, .direction = SM2_FORWARD, };

void TJ_dog_init(void){
  sm2_load_cel_resource("TJ_dog.sm2", cels, LEN(cels));
}
