// Code generated by ase2msx TJ_dog.ase; DO NOT EDIT.
#ifndef TJ_DOG_H_
#define TJ_DOG_H_

#include "sm2.h"
#include "sm2_bmem.h"

extern const sm2_SpriteSheet TJ_dog;
extern const sm2_FrameTag TJ_dog_tag_Walk;

void TJ_dog_init(void);

#endif // TJ_DOG_H_
