// -*- coding: utf-8-unix -*-
/*
 * Copyright (c) 2021-2025 Daishi Mori (mori0091)
 *
 * This software is released under the MIT License.\n
 * See https://github.com/mori0091/libmsx/blob/main/LICENSE
 *
 * GitHub libmsx project\n
 * https://github.com/mori0091/libmsx
 */
/**
 * \file sm2_bmem.h
 * \brief SM2 (Sprite Mode 2) internal APIs for BMEM / Resources.
 * \ingroup SM2
 */

#ifndef SM2_BMEM_H_
#define SM2_BMEM_H_

#include "sm2.h"

/**
 * `MSX2` Load sprite cels.
 *
 * \param name Name of resource that contains list of cel data.
 * \param cels Array of cell objects to be initialized.
 * \param cels_max Number of cels (capacity) of the array.
 * \return Number of cels initialized.
 *
 * \note
 * To initialize a sprite sheet object, this function is called from the sprite
 * sheet initialization function “<your_spritte_sheet_name>_init()”
 * automatically generated by the `ase2msx` tool. Therefore, it is usually not
 * necessary to call this. Call “<your_spritte_sheet_name>_init()” instead.
 */
size_t sm2_load_cel_resource(const char * name, sm2_Cel cels[], size_t cels_max);


#endif // SM2_BMEM_H_
