name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: apt-get update
      run: apt-get update
    - name: apt-get install
      run: apt-get install build-essential sdcc
    - uses: actions/checkout@v2
    - name: make
      run: make
